// this file was autogenerated by arri
// ignore_for_file: type=lint, unused_field, unnecessary_cast
import 'dart:async';
import 'dart:convert';
import 'package:arri_client/arri_client.dart';
import 'package:http/http.dart' as http;

class ArriClient {
  final http.Client? _httpClient;
  final String _baseUrl;
  final String _clientVersion = "";
  final FutureOr<Map<String, String>> Function()? _headers;
  final Function(Object)? _onError;
  final int? _heartbeatTimeoutMultiplier;
  final Duration? _timeout;
  ArriClient({
    http.Client? httpClient,
    required String baseUrl,
    FutureOr<Map<String, String>> Function()? headers,
    Function(Object)? onError,
    int? heartbeatTimeoutMultiplier,
    Duration? timeout,
  }) : _httpClient = httpClient,
       _baseUrl = baseUrl,
       _headers = headers,
       _onError = onError,
       _heartbeatTimeoutMultiplier = heartbeatTimeoutMultiplier,
       _timeout = timeout;

  ArriClientAdminService get admin => ArriClientAdminService(
    baseUrl: _baseUrl,
    headers: _headers,
    httpClient: _httpClient,
    onError: _onError,
    heartbeatTimeoutMultiplier: _heartbeatTimeoutMultiplier,
    timeout: _timeout,
  );

  ArriClientSvgService get svg => ArriClientSvgService(
    baseUrl: _baseUrl,
    headers: _headers,
    httpClient: _httpClient,
    onError: _onError,
    heartbeatTimeoutMultiplier: _heartbeatTimeoutMultiplier,
    timeout: _timeout,
  );
}

class ArriClientAdminService {
  final http.Client? _httpClient;
  final String _baseUrl;
  final String _clientVersion = "";
  final FutureOr<Map<String, String>> Function()? _headers;
  final Function(Object)? _onError;
  final int? _heartbeatTimeoutMultiplier;
  final Duration? _timeout;
  ArriClientAdminService({
    http.Client? httpClient,
    required String baseUrl,
    FutureOr<Map<String, String>> Function()? headers,
    Function(Object)? onError,
    int? heartbeatTimeoutMultiplier,
    Duration? timeout,
  }) : _httpClient = httpClient,
       _baseUrl = baseUrl,
       _headers = headers,
       _onError = onError,
       _heartbeatTimeoutMultiplier = heartbeatTimeoutMultiplier,
       _timeout = timeout;

  Future<CreateComponentResponse> create_component(
    CreateComponentParams params,
  ) async {
    return parsedArriRequest(
      "$_baseUrl/admin/create-component",
      method: HttpMethod.post,
      httpClient: _httpClient,
      headers: _headers,
      clientVersion: _clientVersion,
      params: params.toJson(),
      parser: (body) => CreateComponentResponse.fromJsonString(body),
      onError: _onError,
      timeout: _timeout,
    );
  }

  Future<CreateTypeResponse> create_type(CreateTypeParams params) async {
    return parsedArriRequest(
      "$_baseUrl/admin/create-type",
      method: HttpMethod.post,
      httpClient: _httpClient,
      headers: _headers,
      clientVersion: _clientVersion,
      params: params.toJson(),
      parser: (body) => CreateTypeResponse.fromJsonString(body),
      onError: _onError,
      timeout: _timeout,
    );
  }

  Future<GetComponentsResponse> get_components(
    GetComponentsParams params,
  ) async {
    return parsedArriRequest(
      "$_baseUrl/admin/get-components",
      method: HttpMethod.post,
      httpClient: _httpClient,
      headers: _headers,
      clientVersion: _clientVersion,
      params: params.toJson(),
      parser: (body) => GetComponentsResponse.fromJsonString(body),
      onError: _onError,
      timeout: _timeout,
    );
  }

  Future<GetTypesResponse> get_types(GetTypesParams params) async {
    return parsedArriRequest(
      "$_baseUrl/admin/get-types",
      method: HttpMethod.post,
      httpClient: _httpClient,
      headers: _headers,
      clientVersion: _clientVersion,
      params: params.toJson(),
      parser: (body) => GetTypesResponse.fromJsonString(body),
      onError: _onError,
      timeout: _timeout,
    );
  }

  Future<SaveTypeCodeResponse> save_type_code(SaveTypeCodeParams params) async {
    return parsedArriRequest(
      "$_baseUrl/admin/save-type-code",
      method: HttpMethod.post,
      httpClient: _httpClient,
      headers: _headers,
      clientVersion: _clientVersion,
      params: params.toJson(),
      parser: (body) => SaveTypeCodeResponse.fromJsonString(body),
      onError: _onError,
      timeout: _timeout,
    );
  }

  Future<UpdateComponentResponse> update_component(
    UpdateComponentParams params,
  ) async {
    return parsedArriRequest(
      "$_baseUrl/admin/update-component",
      method: HttpMethod.post,
      httpClient: _httpClient,
      headers: _headers,
      clientVersion: _clientVersion,
      params: params.toJson(),
      parser: (body) => UpdateComponentResponse.fromJsonString(body),
      onError: _onError,
      timeout: _timeout,
    );
  }

  Future<UpdateTypeDefinitionResponse> update_type_definition(
    UpdateTypeDefinitionParams params,
  ) async {
    return parsedArriRequest(
      "$_baseUrl/admin/update-type-definition",
      method: HttpMethod.post,
      httpClient: _httpClient,
      headers: _headers,
      clientVersion: _clientVersion,
      params: params.toJson(),
      parser: (body) => UpdateTypeDefinitionResponse.fromJsonString(body),
      onError: _onError,
      timeout: _timeout,
    );
  }
}

class ArriClientSvgService {
  final http.Client? _httpClient;
  final String _baseUrl;
  final String _clientVersion = "";
  final FutureOr<Map<String, String>> Function()? _headers;
  final Function(Object)? _onError;
  final int? _heartbeatTimeoutMultiplier;
  final Duration? _timeout;
  ArriClientSvgService({
    http.Client? httpClient,
    required String baseUrl,
    FutureOr<Map<String, String>> Function()? headers,
    Function(Object)? onError,
    int? heartbeatTimeoutMultiplier,
    Duration? timeout,
  }) : _httpClient = httpClient,
       _baseUrl = baseUrl,
       _headers = headers,
       _onError = onError,
       _heartbeatTimeoutMultiplier = heartbeatTimeoutMultiplier,
       _timeout = timeout;

  Future<GetSvgsResponse> get_svgs(GetSvgsParams params) async {
    return parsedArriRequest(
      "$_baseUrl/svg/get-svgs",
      method: HttpMethod.post,
      httpClient: _httpClient,
      headers: _headers,
      clientVersion: _clientVersion,
      params: params.toJson(),
      parser: (body) => GetSvgsResponse.fromJsonString(body),
      onError: _onError,
      timeout: _timeout,
    );
  }
}

class CreateComponentParams implements ArriModel {
  final String name;
  final String className;
  final List<CreateComponentParamsPropertiesElement> properties;
  final String? componentCode;
  const CreateComponentParams({
    required this.name,
    required this.className,
    required this.properties,
    this.componentCode,
  });

  factory CreateComponentParams.empty() {
    return CreateComponentParams(name: "", className: "", properties: []);
  }

  factory CreateComponentParams.fromJson(Map<String, dynamic> _input_) {
    final name = typeFromDynamic<String>(_input_["name"], "");
    final className = typeFromDynamic<String>(_input_["className"], "");
    final properties = _input_["properties"] is List
        ? (_input_["properties"] as List)
              .map(
                (_el_) => _el_ is Map<String, dynamic>
                    ? CreateComponentParamsPropertiesElement.fromJson(_el_)
                    : CreateComponentParamsPropertiesElement.empty(),
              )
              .toList()
        : <CreateComponentParamsPropertiesElement>[];
    final componentCode = nullableTypeFromDynamic<String>(
      _input_["componentCode"],
    );
    return CreateComponentParams(
      name: name,
      className: className,
      properties: properties,
      componentCode: componentCode,
    );
  }

  factory CreateComponentParams.fromJsonString(String input) {
    return CreateComponentParams.fromJson(json.decode(input));
  }

  @override
  Map<String, dynamic> toJson() {
    final _output_ = <String, dynamic>{
      "name": name,
      "className": className,
      "properties": properties.map((_el_) => _el_.toJson()).toList(),
    };
    if (componentCode != null) _output_["componentCode"] = componentCode;
    return _output_;
  }

  @override
  String toJsonString() {
    return json.encode(toJson());
  }

  @override
  String toUrlQueryParams() {
    final _queryParts_ = <String>[];
    _queryParts_.add("name=$name");
    _queryParts_.add("className=$className");
    print(
      "[WARNING] arrays cannot be serialized to query params. Skipping field at /CreateComponentParams/properties.",
    );
    if (componentCode != null) _queryParts_.add("componentCode=$componentCode");
    return _queryParts_.join("&");
  }

  @override
  CreateComponentParams copyWith({
    String? name,
    String? className,
    List<CreateComponentParamsPropertiesElement>? properties,
    String? Function()? componentCode,
  }) {
    return CreateComponentParams(
      name: name ?? this.name,
      className: className ?? this.className,
      properties: properties ?? this.properties,
      componentCode: componentCode != null
          ? componentCode()
          : this.componentCode,
    );
  }

  @override
  List<Object?> get props => [name, className, properties, componentCode];

  @override
  bool operator ==(Object other) {
    return other is CreateComponentParams && listsAreEqual(props, other.props);
  }

  @override
  int get hashCode => listToHashCode(props);

  @override
  String toString() {
    return "CreateComponentParams ${toJsonString()}";
  }
}

class CreateComponentParamsPropertiesElement implements ArriModel {
  final String name;
  final String type;
  final String initialValue;
  const CreateComponentParamsPropertiesElement({
    required this.name,
    required this.type,
    required this.initialValue,
  });

  factory CreateComponentParamsPropertiesElement.empty() {
    return CreateComponentParamsPropertiesElement(
      name: "",
      type: "",
      initialValue: "",
    );
  }

  factory CreateComponentParamsPropertiesElement.fromJson(
    Map<String, dynamic> _input_,
  ) {
    final name = typeFromDynamic<String>(_input_["name"], "");
    final type = typeFromDynamic<String>(_input_["type"], "");
    final initialValue = typeFromDynamic<String>(_input_["initialValue"], "");
    return CreateComponentParamsPropertiesElement(
      name: name,
      type: type,
      initialValue: initialValue,
    );
  }

  factory CreateComponentParamsPropertiesElement.fromJsonString(String input) {
    return CreateComponentParamsPropertiesElement.fromJson(json.decode(input));
  }

  @override
  Map<String, dynamic> toJson() {
    final _output_ = <String, dynamic>{
      "name": name,
      "type": type,
      "initialValue": initialValue,
    };

    return _output_;
  }

  @override
  String toJsonString() {
    return json.encode(toJson());
  }

  @override
  String toUrlQueryParams() {
    final _queryParts_ = <String>[];
    _queryParts_.add("name=$name");
    _queryParts_.add("type=$type");
    _queryParts_.add("initialValue=$initialValue");
    return _queryParts_.join("&");
  }

  @override
  CreateComponentParamsPropertiesElement copyWith({
    String? name,
    String? type,
    String? initialValue,
  }) {
    return CreateComponentParamsPropertiesElement(
      name: name ?? this.name,
      type: type ?? this.type,
      initialValue: initialValue ?? this.initialValue,
    );
  }

  @override
  List<Object?> get props => [name, type, initialValue];

  @override
  bool operator ==(Object other) {
    return other is CreateComponentParamsPropertiesElement &&
        listsAreEqual(props, other.props);
  }

  @override
  int get hashCode => listToHashCode(props);

  @override
  String toString() {
    return "CreateComponentParamsPropertiesElement ${toJsonString()}";
  }
}

class CreateComponentResponse implements ArriModel {
  final bool success;
  final String message;
  const CreateComponentResponse({required this.success, required this.message});

  factory CreateComponentResponse.empty() {
    return CreateComponentResponse(success: false, message: "");
  }

  factory CreateComponentResponse.fromJson(Map<String, dynamic> _input_) {
    final success = typeFromDynamic<bool>(_input_["success"], false);
    final message = typeFromDynamic<String>(_input_["message"], "");
    return CreateComponentResponse(success: success, message: message);
  }

  factory CreateComponentResponse.fromJsonString(String input) {
    return CreateComponentResponse.fromJson(json.decode(input));
  }

  @override
  Map<String, dynamic> toJson() {
    final _output_ = <String, dynamic>{"success": success, "message": message};

    return _output_;
  }

  @override
  String toJsonString() {
    return json.encode(toJson());
  }

  @override
  String toUrlQueryParams() {
    final _queryParts_ = <String>[];
    _queryParts_.add("success=$success");
    _queryParts_.add("message=$message");
    return _queryParts_.join("&");
  }

  @override
  CreateComponentResponse copyWith({bool? success, String? message}) {
    return CreateComponentResponse(
      success: success ?? this.success,
      message: message ?? this.message,
    );
  }

  @override
  List<Object?> get props => [success, message];

  @override
  bool operator ==(Object other) {
    return other is CreateComponentResponse &&
        listsAreEqual(props, other.props);
  }

  @override
  int get hashCode => listToHashCode(props);

  @override
  String toString() {
    return "CreateComponentResponse ${toJsonString()}";
  }
}

class CreateTypeParams implements ArriModel {
  final String name;
  final String className;
  final String structure;
  const CreateTypeParams({
    required this.name,
    required this.className,
    required this.structure,
  });

  factory CreateTypeParams.empty() {
    return CreateTypeParams(name: "", className: "", structure: "");
  }

  factory CreateTypeParams.fromJson(Map<String, dynamic> _input_) {
    final name = typeFromDynamic<String>(_input_["name"], "");
    final className = typeFromDynamic<String>(_input_["className"], "");
    final structure = typeFromDynamic<String>(_input_["structure"], "");
    return CreateTypeParams(
      name: name,
      className: className,
      structure: structure,
    );
  }

  factory CreateTypeParams.fromJsonString(String input) {
    return CreateTypeParams.fromJson(json.decode(input));
  }

  @override
  Map<String, dynamic> toJson() {
    final _output_ = <String, dynamic>{
      "name": name,
      "className": className,
      "structure": structure,
    };

    return _output_;
  }

  @override
  String toJsonString() {
    return json.encode(toJson());
  }

  @override
  String toUrlQueryParams() {
    final _queryParts_ = <String>[];
    _queryParts_.add("name=$name");
    _queryParts_.add("className=$className");
    _queryParts_.add("structure=$structure");
    return _queryParts_.join("&");
  }

  @override
  CreateTypeParams copyWith({
    String? name,
    String? className,
    String? structure,
  }) {
    return CreateTypeParams(
      name: name ?? this.name,
      className: className ?? this.className,
      structure: structure ?? this.structure,
    );
  }

  @override
  List<Object?> get props => [name, className, structure];

  @override
  bool operator ==(Object other) {
    return other is CreateTypeParams && listsAreEqual(props, other.props);
  }

  @override
  int get hashCode => listToHashCode(props);

  @override
  String toString() {
    return "CreateTypeParams ${toJsonString()}";
  }
}

class CreateTypeResponse implements ArriModel {
  final bool success;
  final String message;
  const CreateTypeResponse({required this.success, required this.message});

  factory CreateTypeResponse.empty() {
    return CreateTypeResponse(success: false, message: "");
  }

  factory CreateTypeResponse.fromJson(Map<String, dynamic> _input_) {
    final success = typeFromDynamic<bool>(_input_["success"], false);
    final message = typeFromDynamic<String>(_input_["message"], "");
    return CreateTypeResponse(success: success, message: message);
  }

  factory CreateTypeResponse.fromJsonString(String input) {
    return CreateTypeResponse.fromJson(json.decode(input));
  }

  @override
  Map<String, dynamic> toJson() {
    final _output_ = <String, dynamic>{"success": success, "message": message};

    return _output_;
  }

  @override
  String toJsonString() {
    return json.encode(toJson());
  }

  @override
  String toUrlQueryParams() {
    final _queryParts_ = <String>[];
    _queryParts_.add("success=$success");
    _queryParts_.add("message=$message");
    return _queryParts_.join("&");
  }

  @override
  CreateTypeResponse copyWith({bool? success, String? message}) {
    return CreateTypeResponse(
      success: success ?? this.success,
      message: message ?? this.message,
    );
  }

  @override
  List<Object?> get props => [success, message];

  @override
  bool operator ==(Object other) {
    return other is CreateTypeResponse && listsAreEqual(props, other.props);
  }

  @override
  int get hashCode => listToHashCode(props);

  @override
  String toString() {
    return "CreateTypeResponse ${toJsonString()}";
  }
}

class GetComponentsParams implements ArriModel {
  const GetComponentsParams();

  factory GetComponentsParams.empty() {
    return GetComponentsParams();
  }

  factory GetComponentsParams.fromJson(Map<String, dynamic> _input_) {
    return GetComponentsParams();
  }

  factory GetComponentsParams.fromJsonString(String input) {
    return GetComponentsParams.fromJson(json.decode(input));
  }

  @override
  Map<String, dynamic> toJson() {
    final _output_ = <String, dynamic>{};

    return _output_;
  }

  @override
  String toJsonString() {
    return json.encode(toJson());
  }

  @override
  String toUrlQueryParams() {
    final _queryParts_ = <String>[];

    return _queryParts_.join("&");
  }

  @override
  GetComponentsParams copyWith() {
    return GetComponentsParams();
  }

  @override
  List<Object?> get props => [];

  @override
  bool operator ==(Object other) {
    return other is GetComponentsParams && listsAreEqual(props, other.props);
  }

  @override
  int get hashCode => listToHashCode(props);

  @override
  String toString() {
    return "GetComponentsParams ${toJsonString()}";
  }
}

class GetComponentsResponse implements ArriModel {
  final bool success;
  final String message;
  final List<ComponentInfo> components;
  const GetComponentsResponse({
    required this.success,
    required this.message,
    required this.components,
  });

  factory GetComponentsResponse.empty() {
    return GetComponentsResponse(success: false, message: "", components: []);
  }

  factory GetComponentsResponse.fromJson(Map<String, dynamic> _input_) {
    final success = typeFromDynamic<bool>(_input_["success"], false);
    final message = typeFromDynamic<String>(_input_["message"], "");
    final components = _input_["components"] is List
        ? (_input_["components"] as List)
              .map(
                (_el_) => _el_ is Map<String, dynamic>
                    ? ComponentInfo.fromJson(_el_)
                    : ComponentInfo.empty(),
              )
              .toList()
        : <ComponentInfo>[];
    return GetComponentsResponse(
      success: success,
      message: message,
      components: components,
    );
  }

  factory GetComponentsResponse.fromJsonString(String input) {
    return GetComponentsResponse.fromJson(json.decode(input));
  }

  @override
  Map<String, dynamic> toJson() {
    final _output_ = <String, dynamic>{
      "success": success,
      "message": message,
      "components": components.map((_el_) => _el_.toJson()).toList(),
    };

    return _output_;
  }

  @override
  String toJsonString() {
    return json.encode(toJson());
  }

  @override
  String toUrlQueryParams() {
    final _queryParts_ = <String>[];
    _queryParts_.add("success=$success");
    _queryParts_.add("message=$message");
    print(
      "[WARNING] arrays cannot be serialized to query params. Skipping field at /GetComponentsResponse/components.",
    );
    return _queryParts_.join("&");
  }

  @override
  GetComponentsResponse copyWith({
    bool? success,
    String? message,
    List<ComponentInfo>? components,
  }) {
    return GetComponentsResponse(
      success: success ?? this.success,
      message: message ?? this.message,
      components: components ?? this.components,
    );
  }

  @override
  List<Object?> get props => [success, message, components];

  @override
  bool operator ==(Object other) {
    return other is GetComponentsResponse && listsAreEqual(props, other.props);
  }

  @override
  int get hashCode => listToHashCode(props);

  @override
  String toString() {
    return "GetComponentsResponse ${toJsonString()}";
  }
}

class ComponentInfo implements ArriModel {
  final String id;
  final String name;
  final String className;
  final String path;
  final String properties;
  final String code;
  const ComponentInfo({
    required this.id,
    required this.name,
    required this.className,
    required this.path,
    required this.properties,
    required this.code,
  });

  factory ComponentInfo.empty() {
    return ComponentInfo(
      id: "",
      name: "",
      className: "",
      path: "",
      properties: "",
      code: "",
    );
  }

  factory ComponentInfo.fromJson(Map<String, dynamic> _input_) {
    final id = typeFromDynamic<String>(_input_["id"], "");
    final name = typeFromDynamic<String>(_input_["name"], "");
    final className = typeFromDynamic<String>(_input_["className"], "");
    final path = typeFromDynamic<String>(_input_["path"], "");
    final properties = typeFromDynamic<String>(_input_["properties"], "");
    final code = typeFromDynamic<String>(_input_["code"], "");
    return ComponentInfo(
      id: id,
      name: name,
      className: className,
      path: path,
      properties: properties,
      code: code,
    );
  }

  factory ComponentInfo.fromJsonString(String input) {
    return ComponentInfo.fromJson(json.decode(input));
  }

  @override
  Map<String, dynamic> toJson() {
    final _output_ = <String, dynamic>{
      "id": id,
      "name": name,
      "className": className,
      "path": path,
      "properties": properties,
      "code": code,
    };

    return _output_;
  }

  @override
  String toJsonString() {
    return json.encode(toJson());
  }

  @override
  String toUrlQueryParams() {
    final _queryParts_ = <String>[];
    _queryParts_.add("id=$id");
    _queryParts_.add("name=$name");
    _queryParts_.add("className=$className");
    _queryParts_.add("path=$path");
    _queryParts_.add("properties=$properties");
    _queryParts_.add("code=$code");
    return _queryParts_.join("&");
  }

  @override
  ComponentInfo copyWith({
    String? id,
    String? name,
    String? className,
    String? path,
    String? properties,
    String? code,
  }) {
    return ComponentInfo(
      id: id ?? this.id,
      name: name ?? this.name,
      className: className ?? this.className,
      path: path ?? this.path,
      properties: properties ?? this.properties,
      code: code ?? this.code,
    );
  }

  @override
  List<Object?> get props => [id, name, className, path, properties, code];

  @override
  bool operator ==(Object other) {
    return other is ComponentInfo && listsAreEqual(props, other.props);
  }

  @override
  int get hashCode => listToHashCode(props);

  @override
  String toString() {
    return "ComponentInfo ${toJsonString()}";
  }
}

class GetTypesParams implements ArriModel {
  const GetTypesParams();

  factory GetTypesParams.empty() {
    return GetTypesParams();
  }

  factory GetTypesParams.fromJson(Map<String, dynamic> _input_) {
    return GetTypesParams();
  }

  factory GetTypesParams.fromJsonString(String input) {
    return GetTypesParams.fromJson(json.decode(input));
  }

  @override
  Map<String, dynamic> toJson() {
    final _output_ = <String, dynamic>{};

    return _output_;
  }

  @override
  String toJsonString() {
    return json.encode(toJson());
  }

  @override
  String toUrlQueryParams() {
    final _queryParts_ = <String>[];

    return _queryParts_.join("&");
  }

  @override
  GetTypesParams copyWith() {
    return GetTypesParams();
  }

  @override
  List<Object?> get props => [];

  @override
  bool operator ==(Object other) {
    return other is GetTypesParams && listsAreEqual(props, other.props);
  }

  @override
  int get hashCode => listToHashCode(props);

  @override
  String toString() {
    return "GetTypesParams ${toJsonString()}";
  }
}

class GetTypesResponse implements ArriModel {
  final bool success;
  final String message;
  final List<Type> types;
  const GetTypesResponse({
    required this.success,
    required this.message,
    required this.types,
  });

  factory GetTypesResponse.empty() {
    return GetTypesResponse(success: false, message: "", types: []);
  }

  factory GetTypesResponse.fromJson(Map<String, dynamic> _input_) {
    final success = typeFromDynamic<bool>(_input_["success"], false);
    final message = typeFromDynamic<String>(_input_["message"], "");
    final types = _input_["types"] is List
        ? (_input_["types"] as List)
              .map(
                (_el_) => _el_ is Map<String, dynamic>
                    ? Type.fromJson(_el_)
                    : Type.empty(),
              )
              .toList()
        : <Type>[];
    return GetTypesResponse(success: success, message: message, types: types);
  }

  factory GetTypesResponse.fromJsonString(String input) {
    return GetTypesResponse.fromJson(json.decode(input));
  }

  @override
  Map<String, dynamic> toJson() {
    final _output_ = <String, dynamic>{
      "success": success,
      "message": message,
      "types": types.map((_el_) => _el_.toJson()).toList(),
    };

    return _output_;
  }

  @override
  String toJsonString() {
    return json.encode(toJson());
  }

  @override
  String toUrlQueryParams() {
    final _queryParts_ = <String>[];
    _queryParts_.add("success=$success");
    _queryParts_.add("message=$message");
    print(
      "[WARNING] arrays cannot be serialized to query params. Skipping field at /GetTypesResponse/types.",
    );
    return _queryParts_.join("&");
  }

  @override
  GetTypesResponse copyWith({
    bool? success,
    String? message,
    List<Type>? types,
  }) {
    return GetTypesResponse(
      success: success ?? this.success,
      message: message ?? this.message,
      types: types ?? this.types,
    );
  }

  @override
  List<Object?> get props => [success, message, types];

  @override
  bool operator ==(Object other) {
    return other is GetTypesResponse && listsAreEqual(props, other.props);
  }

  @override
  int get hashCode => listToHashCode(props);

  @override
  String toString() {
    return "GetTypesResponse ${toJsonString()}";
  }
}

class Type implements ArriModel {
  final String id;
  final String name;
  final String className;
  final String path;
  final String code;
  final String structure;
  final String enumValues;
  final String createdAt;
  final String updatedAt;
  const Type({
    required this.id,
    required this.name,
    required this.className,
    required this.path,
    required this.code,
    required this.structure,
    required this.enumValues,
    required this.createdAt,
    required this.updatedAt,
  });

  factory Type.empty() {
    return Type(
      id: "",
      name: "",
      className: "",
      path: "",
      code: "",
      structure: "",
      enumValues: "",
      createdAt: "",
      updatedAt: "",
    );
  }

  factory Type.fromJson(Map<String, dynamic> _input_) {
    final id = typeFromDynamic<String>(_input_["id"], "");
    final name = typeFromDynamic<String>(_input_["name"], "");
    final className = typeFromDynamic<String>(_input_["className"], "");
    final path = typeFromDynamic<String>(_input_["path"], "");
    final code = typeFromDynamic<String>(_input_["code"], "");
    final structure = typeFromDynamic<String>(_input_["structure"], "");
    final enumValues = typeFromDynamic<String>(_input_["enumValues"], "");
    final createdAt = typeFromDynamic<String>(_input_["createdAt"], "");
    final updatedAt = typeFromDynamic<String>(_input_["updatedAt"], "");
    return Type(
      id: id,
      name: name,
      className: className,
      path: path,
      code: code,
      structure: structure,
      enumValues: enumValues,
      createdAt: createdAt,
      updatedAt: updatedAt,
    );
  }

  factory Type.fromJsonString(String input) {
    return Type.fromJson(json.decode(input));
  }

  @override
  Map<String, dynamic> toJson() {
    final _output_ = <String, dynamic>{
      "id": id,
      "name": name,
      "className": className,
      "path": path,
      "code": code,
      "structure": structure,
      "enumValues": enumValues,
      "createdAt": createdAt,
      "updatedAt": updatedAt,
    };

    return _output_;
  }

  @override
  String toJsonString() {
    return json.encode(toJson());
  }

  @override
  String toUrlQueryParams() {
    final _queryParts_ = <String>[];
    _queryParts_.add("id=$id");
    _queryParts_.add("name=$name");
    _queryParts_.add("className=$className");
    _queryParts_.add("path=$path");
    _queryParts_.add("code=$code");
    _queryParts_.add("structure=$structure");
    _queryParts_.add("enumValues=$enumValues");
    _queryParts_.add("createdAt=$createdAt");
    _queryParts_.add("updatedAt=$updatedAt");
    return _queryParts_.join("&");
  }

  @override
  Type copyWith({
    String? id,
    String? name,
    String? className,
    String? path,
    String? code,
    String? structure,
    String? enumValues,
    String? createdAt,
    String? updatedAt,
  }) {
    return Type(
      id: id ?? this.id,
      name: name ?? this.name,
      className: className ?? this.className,
      path: path ?? this.path,
      code: code ?? this.code,
      structure: structure ?? this.structure,
      enumValues: enumValues ?? this.enumValues,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
    );
  }

  @override
  List<Object?> get props => [
    id,
    name,
    className,
    path,
    code,
    structure,
    enumValues,
    createdAt,
    updatedAt,
  ];

  @override
  bool operator ==(Object other) {
    return other is Type && listsAreEqual(props, other.props);
  }

  @override
  int get hashCode => listToHashCode(props);

  @override
  String toString() {
    return "Type ${toJsonString()}";
  }
}

class SaveTypeCodeParams implements ArriModel {
  final String typeId;
  final String code;
  const SaveTypeCodeParams({required this.typeId, required this.code});

  factory SaveTypeCodeParams.empty() {
    return SaveTypeCodeParams(typeId: "", code: "");
  }

  factory SaveTypeCodeParams.fromJson(Map<String, dynamic> _input_) {
    final typeId = typeFromDynamic<String>(_input_["typeId"], "");
    final code = typeFromDynamic<String>(_input_["code"], "");
    return SaveTypeCodeParams(typeId: typeId, code: code);
  }

  factory SaveTypeCodeParams.fromJsonString(String input) {
    return SaveTypeCodeParams.fromJson(json.decode(input));
  }

  @override
  Map<String, dynamic> toJson() {
    final _output_ = <String, dynamic>{"typeId": typeId, "code": code};

    return _output_;
  }

  @override
  String toJsonString() {
    return json.encode(toJson());
  }

  @override
  String toUrlQueryParams() {
    final _queryParts_ = <String>[];
    _queryParts_.add("typeId=$typeId");
    _queryParts_.add("code=$code");
    return _queryParts_.join("&");
  }

  @override
  SaveTypeCodeParams copyWith({String? typeId, String? code}) {
    return SaveTypeCodeParams(
      typeId: typeId ?? this.typeId,
      code: code ?? this.code,
    );
  }

  @override
  List<Object?> get props => [typeId, code];

  @override
  bool operator ==(Object other) {
    return other is SaveTypeCodeParams && listsAreEqual(props, other.props);
  }

  @override
  int get hashCode => listToHashCode(props);

  @override
  String toString() {
    return "SaveTypeCodeParams ${toJsonString()}";
  }
}

class SaveTypeCodeResponse implements ArriModel {
  final bool success;
  final String message;
  const SaveTypeCodeResponse({required this.success, required this.message});

  factory SaveTypeCodeResponse.empty() {
    return SaveTypeCodeResponse(success: false, message: "");
  }

  factory SaveTypeCodeResponse.fromJson(Map<String, dynamic> _input_) {
    final success = typeFromDynamic<bool>(_input_["success"], false);
    final message = typeFromDynamic<String>(_input_["message"], "");
    return SaveTypeCodeResponse(success: success, message: message);
  }

  factory SaveTypeCodeResponse.fromJsonString(String input) {
    return SaveTypeCodeResponse.fromJson(json.decode(input));
  }

  @override
  Map<String, dynamic> toJson() {
    final _output_ = <String, dynamic>{"success": success, "message": message};

    return _output_;
  }

  @override
  String toJsonString() {
    return json.encode(toJson());
  }

  @override
  String toUrlQueryParams() {
    final _queryParts_ = <String>[];
    _queryParts_.add("success=$success");
    _queryParts_.add("message=$message");
    return _queryParts_.join("&");
  }

  @override
  SaveTypeCodeResponse copyWith({bool? success, String? message}) {
    return SaveTypeCodeResponse(
      success: success ?? this.success,
      message: message ?? this.message,
    );
  }

  @override
  List<Object?> get props => [success, message];

  @override
  bool operator ==(Object other) {
    return other is SaveTypeCodeResponse && listsAreEqual(props, other.props);
  }

  @override
  int get hashCode => listToHashCode(props);

  @override
  String toString() {
    return "SaveTypeCodeResponse ${toJsonString()}";
  }
}

class UpdateComponentParams implements ArriModel {
  final String id;
  final List<UpdateComponentParamsPropertiesElement> properties;
  final String componentCode;
  const UpdateComponentParams({
    required this.id,
    required this.properties,
    required this.componentCode,
  });

  factory UpdateComponentParams.empty() {
    return UpdateComponentParams(id: "", properties: [], componentCode: "");
  }

  factory UpdateComponentParams.fromJson(Map<String, dynamic> _input_) {
    final id = typeFromDynamic<String>(_input_["id"], "");
    final properties = _input_["properties"] is List
        ? (_input_["properties"] as List)
              .map(
                (_el_) => _el_ is Map<String, dynamic>
                    ? UpdateComponentParamsPropertiesElement.fromJson(_el_)
                    : UpdateComponentParamsPropertiesElement.empty(),
              )
              .toList()
        : <UpdateComponentParamsPropertiesElement>[];
    final componentCode = typeFromDynamic<String>(_input_["componentCode"], "");
    return UpdateComponentParams(
      id: id,
      properties: properties,
      componentCode: componentCode,
    );
  }

  factory UpdateComponentParams.fromJsonString(String input) {
    return UpdateComponentParams.fromJson(json.decode(input));
  }

  @override
  Map<String, dynamic> toJson() {
    final _output_ = <String, dynamic>{
      "id": id,
      "properties": properties.map((_el_) => _el_.toJson()).toList(),
      "componentCode": componentCode,
    };

    return _output_;
  }

  @override
  String toJsonString() {
    return json.encode(toJson());
  }

  @override
  String toUrlQueryParams() {
    final _queryParts_ = <String>[];
    _queryParts_.add("id=$id");
    print(
      "[WARNING] arrays cannot be serialized to query params. Skipping field at /UpdateComponentParams/properties.",
    );
    _queryParts_.add("componentCode=$componentCode");
    return _queryParts_.join("&");
  }

  @override
  UpdateComponentParams copyWith({
    String? id,
    List<UpdateComponentParamsPropertiesElement>? properties,
    String? componentCode,
  }) {
    return UpdateComponentParams(
      id: id ?? this.id,
      properties: properties ?? this.properties,
      componentCode: componentCode ?? this.componentCode,
    );
  }

  @override
  List<Object?> get props => [id, properties, componentCode];

  @override
  bool operator ==(Object other) {
    return other is UpdateComponentParams && listsAreEqual(props, other.props);
  }

  @override
  int get hashCode => listToHashCode(props);

  @override
  String toString() {
    return "UpdateComponentParams ${toJsonString()}";
  }
}

class UpdateComponentParamsPropertiesElement implements ArriModel {
  final String name;
  final UpdateComponentParamsPropertiesElementType type;
  final String initialValue;
  const UpdateComponentParamsPropertiesElement({
    required this.name,
    required this.type,
    required this.initialValue,
  });

  factory UpdateComponentParamsPropertiesElement.empty() {
    return UpdateComponentParamsPropertiesElement(
      name: "",
      type: UpdateComponentParamsPropertiesElementType.string,
      initialValue: "",
    );
  }

  factory UpdateComponentParamsPropertiesElement.fromJson(
    Map<String, dynamic> _input_,
  ) {
    final name = typeFromDynamic<String>(_input_["name"], "");
    final type = UpdateComponentParamsPropertiesElementType.fromString(
      typeFromDynamic<String>(_input_["type"], ""),
    );
    final initialValue = typeFromDynamic<String>(_input_["initialValue"], "");
    return UpdateComponentParamsPropertiesElement(
      name: name,
      type: type,
      initialValue: initialValue,
    );
  }

  factory UpdateComponentParamsPropertiesElement.fromJsonString(String input) {
    return UpdateComponentParamsPropertiesElement.fromJson(json.decode(input));
  }

  @override
  Map<String, dynamic> toJson() {
    final _output_ = <String, dynamic>{
      "name": name,
      "type": type.serialValue,
      "initialValue": initialValue,
    };

    return _output_;
  }

  @override
  String toJsonString() {
    return json.encode(toJson());
  }

  @override
  String toUrlQueryParams() {
    final _queryParts_ = <String>[];
    _queryParts_.add("name=$name");
    _queryParts_.add("type=${type.serialValue}");
    _queryParts_.add("initialValue=$initialValue");
    return _queryParts_.join("&");
  }

  @override
  UpdateComponentParamsPropertiesElement copyWith({
    String? name,
    UpdateComponentParamsPropertiesElementType? type,
    String? initialValue,
  }) {
    return UpdateComponentParamsPropertiesElement(
      name: name ?? this.name,
      type: type ?? this.type,
      initialValue: initialValue ?? this.initialValue,
    );
  }

  @override
  List<Object?> get props => [name, type, initialValue];

  @override
  bool operator ==(Object other) {
    return other is UpdateComponentParamsPropertiesElement &&
        listsAreEqual(props, other.props);
  }

  @override
  int get hashCode => listToHashCode(props);

  @override
  String toString() {
    return "UpdateComponentParamsPropertiesElement ${toJsonString()}";
  }
}

enum UpdateComponentParamsPropertiesElementType
    implements Comparable<UpdateComponentParamsPropertiesElementType> {
  string("string"),
  number("number"),
  boolean("boolean"),
  color("color");

  const UpdateComponentParamsPropertiesElementType(this.serialValue);
  final String serialValue;

  factory UpdateComponentParamsPropertiesElementType.fromString(String input) {
    for (final val in values) {
      if (val.serialValue == input) {
        return val;
      }
    }
    return string;
  }

  @override
  int compareTo(UpdateComponentParamsPropertiesElementType other) =>
      name.compareTo(other.name);
}

class UpdateComponentResponse implements ArriModel {
  final bool success;
  final String message;
  const UpdateComponentResponse({required this.success, required this.message});

  factory UpdateComponentResponse.empty() {
    return UpdateComponentResponse(success: false, message: "");
  }

  factory UpdateComponentResponse.fromJson(Map<String, dynamic> _input_) {
    final success = typeFromDynamic<bool>(_input_["success"], false);
    final message = typeFromDynamic<String>(_input_["message"], "");
    return UpdateComponentResponse(success: success, message: message);
  }

  factory UpdateComponentResponse.fromJsonString(String input) {
    return UpdateComponentResponse.fromJson(json.decode(input));
  }

  @override
  Map<String, dynamic> toJson() {
    final _output_ = <String, dynamic>{"success": success, "message": message};

    return _output_;
  }

  @override
  String toJsonString() {
    return json.encode(toJson());
  }

  @override
  String toUrlQueryParams() {
    final _queryParts_ = <String>[];
    _queryParts_.add("success=$success");
    _queryParts_.add("message=$message");
    return _queryParts_.join("&");
  }

  @override
  UpdateComponentResponse copyWith({bool? success, String? message}) {
    return UpdateComponentResponse(
      success: success ?? this.success,
      message: message ?? this.message,
    );
  }

  @override
  List<Object?> get props => [success, message];

  @override
  bool operator ==(Object other) {
    return other is UpdateComponentResponse &&
        listsAreEqual(props, other.props);
  }

  @override
  int get hashCode => listToHashCode(props);

  @override
  String toString() {
    return "UpdateComponentResponse ${toJsonString()}";
  }
}

class UpdateTypeDefinitionParams implements ArriModel {
  final String typeId;
  final String code;
  final String enumValues;
  final String structure;
  const UpdateTypeDefinitionParams({
    required this.typeId,
    required this.code,
    required this.enumValues,
    required this.structure,
  });

  factory UpdateTypeDefinitionParams.empty() {
    return UpdateTypeDefinitionParams(
      typeId: "",
      code: "",
      enumValues: "",
      structure: "",
    );
  }

  factory UpdateTypeDefinitionParams.fromJson(Map<String, dynamic> _input_) {
    final typeId = typeFromDynamic<String>(_input_["typeId"], "");
    final code = typeFromDynamic<String>(_input_["code"], "");
    final enumValues = typeFromDynamic<String>(_input_["enumValues"], "");
    final structure = typeFromDynamic<String>(_input_["structure"], "");
    return UpdateTypeDefinitionParams(
      typeId: typeId,
      code: code,
      enumValues: enumValues,
      structure: structure,
    );
  }

  factory UpdateTypeDefinitionParams.fromJsonString(String input) {
    return UpdateTypeDefinitionParams.fromJson(json.decode(input));
  }

  @override
  Map<String, dynamic> toJson() {
    final _output_ = <String, dynamic>{
      "typeId": typeId,
      "code": code,
      "enumValues": enumValues,
      "structure": structure,
    };

    return _output_;
  }

  @override
  String toJsonString() {
    return json.encode(toJson());
  }

  @override
  String toUrlQueryParams() {
    final _queryParts_ = <String>[];
    _queryParts_.add("typeId=$typeId");
    _queryParts_.add("code=$code");
    _queryParts_.add("enumValues=$enumValues");
    _queryParts_.add("structure=$structure");
    return _queryParts_.join("&");
  }

  @override
  UpdateTypeDefinitionParams copyWith({
    String? typeId,
    String? code,
    String? enumValues,
    String? structure,
  }) {
    return UpdateTypeDefinitionParams(
      typeId: typeId ?? this.typeId,
      code: code ?? this.code,
      enumValues: enumValues ?? this.enumValues,
      structure: structure ?? this.structure,
    );
  }

  @override
  List<Object?> get props => [typeId, code, enumValues, structure];

  @override
  bool operator ==(Object other) {
    return other is UpdateTypeDefinitionParams &&
        listsAreEqual(props, other.props);
  }

  @override
  int get hashCode => listToHashCode(props);

  @override
  String toString() {
    return "UpdateTypeDefinitionParams ${toJsonString()}";
  }
}

class UpdateTypeDefinitionResponse implements ArriModel {
  final bool success;
  final String message;
  const UpdateTypeDefinitionResponse({
    required this.success,
    required this.message,
  });

  factory UpdateTypeDefinitionResponse.empty() {
    return UpdateTypeDefinitionResponse(success: false, message: "");
  }

  factory UpdateTypeDefinitionResponse.fromJson(Map<String, dynamic> _input_) {
    final success = typeFromDynamic<bool>(_input_["success"], false);
    final message = typeFromDynamic<String>(_input_["message"], "");
    return UpdateTypeDefinitionResponse(success: success, message: message);
  }

  factory UpdateTypeDefinitionResponse.fromJsonString(String input) {
    return UpdateTypeDefinitionResponse.fromJson(json.decode(input));
  }

  @override
  Map<String, dynamic> toJson() {
    final _output_ = <String, dynamic>{"success": success, "message": message};

    return _output_;
  }

  @override
  String toJsonString() {
    return json.encode(toJson());
  }

  @override
  String toUrlQueryParams() {
    final _queryParts_ = <String>[];
    _queryParts_.add("success=$success");
    _queryParts_.add("message=$message");
    return _queryParts_.join("&");
  }

  @override
  UpdateTypeDefinitionResponse copyWith({bool? success, String? message}) {
    return UpdateTypeDefinitionResponse(
      success: success ?? this.success,
      message: message ?? this.message,
    );
  }

  @override
  List<Object?> get props => [success, message];

  @override
  bool operator ==(Object other) {
    return other is UpdateTypeDefinitionResponse &&
        listsAreEqual(props, other.props);
  }

  @override
  int get hashCode => listToHashCode(props);

  @override
  String toString() {
    return "UpdateTypeDefinitionResponse ${toJsonString()}";
  }
}

class GetSvgsParams implements ArriModel {
  final int limit;
  final int offset;
  final String? search;
  const GetSvgsParams({
    required this.limit,
    required this.offset,
    required this.search,
  });

  factory GetSvgsParams.empty() {
    return GetSvgsParams(limit: 0, offset: 0, search: null);
  }

  factory GetSvgsParams.fromJson(Map<String, dynamic> _input_) {
    final limit = intFromDynamic(_input_["limit"], 0);
    final offset = intFromDynamic(_input_["offset"], 0);
    final search = nullableTypeFromDynamic<String>(_input_["search"]);
    return GetSvgsParams(limit: limit, offset: offset, search: search);
  }

  factory GetSvgsParams.fromJsonString(String input) {
    return GetSvgsParams.fromJson(json.decode(input));
  }

  @override
  Map<String, dynamic> toJson() {
    final _output_ = <String, dynamic>{
      "limit": limit,
      "offset": offset,
      "search": search,
    };

    return _output_;
  }

  @override
  String toJsonString() {
    return json.encode(toJson());
  }

  @override
  String toUrlQueryParams() {
    final _queryParts_ = <String>[];
    _queryParts_.add("limit=$limit");
    _queryParts_.add("offset=$offset");
    _queryParts_.add("search=$search");
    return _queryParts_.join("&");
  }

  @override
  GetSvgsParams copyWith({
    int? limit,
    int? offset,
    String? Function()? search,
  }) {
    return GetSvgsParams(
      limit: limit ?? this.limit,
      offset: offset ?? this.offset,
      search: search != null ? search() : this.search,
    );
  }

  @override
  List<Object?> get props => [limit, offset, search];

  @override
  bool operator ==(Object other) {
    return other is GetSvgsParams && listsAreEqual(props, other.props);
  }

  @override
  int get hashCode => listToHashCode(props);

  @override
  String toString() {
    return "GetSvgsParams ${toJsonString()}";
  }
}

class GetSvgsResponse implements ArriModel {
  final bool success;
  final String message;
  final int total;
  final List<SvgInfo> svgs;
  const GetSvgsResponse({
    required this.success,
    required this.message,
    required this.total,
    required this.svgs,
  });

  factory GetSvgsResponse.empty() {
    return GetSvgsResponse(success: false, message: "", total: 0, svgs: []);
  }

  factory GetSvgsResponse.fromJson(Map<String, dynamic> _input_) {
    final success = typeFromDynamic<bool>(_input_["success"], false);
    final message = typeFromDynamic<String>(_input_["message"], "");
    final total = intFromDynamic(_input_["total"], 0);
    final svgs = _input_["svgs"] is List
        ? (_input_["svgs"] as List)
              .map(
                (_el_) => _el_ is Map<String, dynamic>
                    ? SvgInfo.fromJson(_el_)
                    : SvgInfo.empty(),
              )
              .toList()
        : <SvgInfo>[];
    return GetSvgsResponse(
      success: success,
      message: message,
      total: total,
      svgs: svgs,
    );
  }

  factory GetSvgsResponse.fromJsonString(String input) {
    return GetSvgsResponse.fromJson(json.decode(input));
  }

  @override
  Map<String, dynamic> toJson() {
    final _output_ = <String, dynamic>{
      "success": success,
      "message": message,
      "total": total,
      "svgs": svgs.map((_el_) => _el_.toJson()).toList(),
    };

    return _output_;
  }

  @override
  String toJsonString() {
    return json.encode(toJson());
  }

  @override
  String toUrlQueryParams() {
    final _queryParts_ = <String>[];
    _queryParts_.add("success=$success");
    _queryParts_.add("message=$message");
    _queryParts_.add("total=$total");
    print(
      "[WARNING] arrays cannot be serialized to query params. Skipping field at /GetSvgsResponse/svgs.",
    );
    return _queryParts_.join("&");
  }

  @override
  GetSvgsResponse copyWith({
    bool? success,
    String? message,
    int? total,
    List<SvgInfo>? svgs,
  }) {
    return GetSvgsResponse(
      success: success ?? this.success,
      message: message ?? this.message,
      total: total ?? this.total,
      svgs: svgs ?? this.svgs,
    );
  }

  @override
  List<Object?> get props => [success, message, total, svgs];

  @override
  bool operator ==(Object other) {
    return other is GetSvgsResponse && listsAreEqual(props, other.props);
  }

  @override
  int get hashCode => listToHashCode(props);

  @override
  String toString() {
    return "GetSvgsResponse ${toJsonString()}";
  }
}

class SvgInfo implements ArriModel {
  final String id;
  final String name;
  final String svg;
  final String type;
  const SvgInfo({
    required this.id,
    required this.name,
    required this.svg,
    required this.type,
  });

  factory SvgInfo.empty() {
    return SvgInfo(id: "", name: "", svg: "", type: "");
  }

  factory SvgInfo.fromJson(Map<String, dynamic> _input_) {
    final id = typeFromDynamic<String>(_input_["id"], "");
    final name = typeFromDynamic<String>(_input_["name"], "");
    final svg = typeFromDynamic<String>(_input_["svg"], "");
    final type = typeFromDynamic<String>(_input_["type"], "");
    return SvgInfo(id: id, name: name, svg: svg, type: type);
  }

  factory SvgInfo.fromJsonString(String input) {
    return SvgInfo.fromJson(json.decode(input));
  }

  @override
  Map<String, dynamic> toJson() {
    final _output_ = <String, dynamic>{
      "id": id,
      "name": name,
      "svg": svg,
      "type": type,
    };

    return _output_;
  }

  @override
  String toJsonString() {
    return json.encode(toJson());
  }

  @override
  String toUrlQueryParams() {
    final _queryParts_ = <String>[];
    _queryParts_.add("id=$id");
    _queryParts_.add("name=$name");
    _queryParts_.add("svg=$svg");
    _queryParts_.add("type=$type");
    return _queryParts_.join("&");
  }

  @override
  SvgInfo copyWith({String? id, String? name, String? svg, String? type}) {
    return SvgInfo(
      id: id ?? this.id,
      name: name ?? this.name,
      svg: svg ?? this.svg,
      type: type ?? this.type,
    );
  }

  @override
  List<Object?> get props => [id, name, svg, type];

  @override
  bool operator ==(Object other) {
    return other is SvgInfo && listsAreEqual(props, other.props);
  }

  @override
  int get hashCode => listToHashCode(props);

  @override
  String toString() {
    return "SvgInfo ${toJsonString()}";
  }
}
