import { pgTable, text, varchar, timestamp, index, foreignKey } from 'drizzle-orm/pg-core';
import { ulidField, defaultDateFields } from './common';

export const aiDesignSessions = pgTable('ai_design_sessions', {
    id: ulidField('id').primaryKey(), // Usually generated by frontend
    ...defaultDateFields,
});

export const aiDesignMessages = pgTable('ai_design_messages', {
    id: ulidField('id').primaryKey(),
    sessionId: ulidField('session_id').notNull().references(() => aiDesignSessions.id, { onDelete: 'cascade' }),
    role: varchar('role', { length: 20 }).notNull(), // 'user' | 'assistant'
    content: text('content').notNull(), // Prompt or JSON
    createdAt: timestamp('created_at', { mode: 'date' }).notNull().defaultNow(),
}, (table) => {
    return {
        sessionIdx: index('ai_design_messages_session_idx').on(table.sessionId),
    };
});

export type AiDesignSession = typeof aiDesignSessions.$inferSelect;
export type NewAiDesignSession = typeof aiDesignSessions.$inferInsert;

export type AiDesignMessage = typeof aiDesignMessages.$inferSelect;
export type NewAiDesignMessage = typeof aiDesignMessages.$inferInsert;
