import sourceMapSupport from "source-map-support";
sourceMapSupport.install();
import app from "../src/app";
import adminCreateComponent from "./../src/procedures/admin/create_component.rpc";
import adminCreateType from "./../src/procedures/admin/create_type.rpc";
import adminGetComponents from "./../src/procedures/admin/get_components.rpc";
import adminGetTypes from "./../src/procedures/admin/get_types.rpc";
import adminSaveTypeCode from "./../src/procedures/admin/save_type_code.rpc";
import adminUpdateComponent from "./../src/procedures/admin/update_component.rpc";
import adminUpdateTypeDefinition from "./../src/procedures/admin/update_type_definition.rpc";
import aiEditImage from "./../src/procedures/ai/edit_image.rpc";
import aiGenerateDesign from "./../src/procedures/ai/generate_design.rpc";
import aiGenerateImage from "./../src/procedures/ai/generate_image.rpc";
import aiGenerateWithPreview from "./../src/procedures/ai/generate_with_preview.rpc";
import aiInpaintImage from "./../src/procedures/ai/inpaint_image.rpc";
import aiIterateDesign from "./../src/procedures/ai/iterate_design.rpc";
import screensCreateScreen from "./../src/procedures/screens/create_screen.rpc";
import screensDeleteScreen from "./../src/procedures/screens/delete_screen.rpc";
import screensGetScreens from "./../src/procedures/screens/get_screens.rpc";
import screensUpdateScreen from "./../src/procedures/screens/update_screen.rpc";
import svgGetSvgs from "./../src/procedures/svg/get_svgs.rpc";

app.rpc("admin.create_component", adminCreateComponent);
app.rpc("admin.create_type", adminCreateType);
app.rpc("admin.get_components", adminGetComponents);
app.rpc("admin.get_types", adminGetTypes);
app.rpc("admin.save_type_code", adminSaveTypeCode);
app.rpc("admin.update_component", adminUpdateComponent);
app.rpc("admin.update_type_definition", adminUpdateTypeDefinition);
app.rpc("ai.edit_image", aiEditImage);
app.rpc("ai.generate_design", aiGenerateDesign);
app.rpc("ai.generate_image", aiGenerateImage);
app.rpc("ai.generate_with_preview", aiGenerateWithPreview);
app.rpc("ai.inpaint_image", aiInpaintImage);
app.rpc("ai.iterate_design", aiIterateDesign);
app.rpc("screens.create_screen", screensCreateScreen);
app.rpc("screens.delete_screen", screensDeleteScreen);
app.rpc("screens.get_screens", screensGetScreens);
app.rpc("screens.update_screen", screensUpdateScreen);
app.rpc("svg.get_svgs", svgGetSvgs);

export default app;
